name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 24.0.1+9
      uses: actions/setup-java@v4
      with:
        java-version: 1.8
        distribution: 'temurin'
